server {
    listen 80;
    server_name knackeredlad.au;

    root /usr/share/nginx/html;
    index index.html;

    location /assets/ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
