sonar.organization=wyeu0008-stu
sonar.projectKey=wyeu0008-stu_SmartCityTool

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=src/**/*.{spec,test}.{js,ts,jsx,tsx}
sonar.exclusions=node_modules/**,dist/**,coverage/**,.github/**
sonar.coverage.exclusions=src/**/*.spec.js,src/**/*.test.js
sonar.cpd.exclusions=src/**/*.spec.js,src/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info